// <auto-generated />
using System;
using MVCSandBox.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCSandBox.Migrations
{
    [DbContext(typeof(MvcSandboxContext))]
    [Migration("20220602010143_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("MVCSandBox.Models.MovDetalheLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResumoLancDiaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResumoLancDiaId");

                    b.ToTable("MovDetalheLancamentos");
                });

            modelBuilder.Entity("MVCSandBox.Models.MovResumoLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MovResumoLancamentos");
                });

            modelBuilder.Entity("MVCSandBox.Models.MovDetalheLancamento", b =>
                {
                    b.HasOne("MVCSandBox.Models.MovResumoLancamento", "ResumoLancDia")
                        .WithMany("DetLancDias")
                        .HasForeignKey("ResumoLancDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumoLancDia");
                });

            modelBuilder.Entity("MVCSandBox.Models.MovResumoLancamento", b =>
                {
                    b.Navigation("DetLancDias");
                });
#pragma warning restore 612, 618
        }
    }
}
